version: '3.8'

services:

  mongodb:
    image: mongo:latest
    command: mongod --port 27017
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: github
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - github-events-services-network

  collector:
    build:
      context: ../
      dockerfile: ./collector/Dockerfile
    container_name: events-collector
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_URL=mongodb
      - MONGO_DB_PORT=27017
    networks:
      - github-events-services-network

  api:
    build:
      context: ../
      dockerfile: ./api/Dockerfile
    container_name: events-api
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_URL=mongodb
      - MONGO_DB_PORT=27017
    ports:
      - '8080:8080'
    networks:
      - github-events-services-network

networks:
  github-events-services-network:
    driver: bridge